example/brid/config/routes.rb
Rails.application.routes.draw do
  resources :interactions
  resources :services
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "main/index"
  get "main/export"
  post "main/connect"
  post "main/interact"

  resources :natural_people

  root "main#index"

end

example/brid/app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  before_action :set_interaction, only: [:show, :edit, :update, :destroy]

  # GET /interactions
  # GET /interactions.json
  def index
    @interactions = Interaction.all
  end

  # GET /interactions/1
  # GET /interactions/1.json
  def show
  end

  # GET /interactions/new
  def new
    @interaction = Interaction.new
  end

  # GET /interactions/1/edit
  def edit
  end

  # POST /interactions
  # POST /interactions.json
  def create
    @interaction = Interaction.new(interaction_params)

    respond_to do |format|
      if @interaction.save
        format.html { redirect_to @interaction, notice: 'Interaction was successfully created.' }
        format.json { render :show, status: :created, location: @interaction }
      else
        format.html { render :new }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interactions/1
  # PATCH/PUT /interactions/1.json
  def update
    respond_to do |format|
      if @interaction.update(interaction_params)
        format.html { redirect_to @interaction, notice: 'Interaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @interaction }
      else
        format.html { render :edit }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interactions/1
  # DELETE /interactions/1.json
  def destroy
    @interaction.destroy
    respond_to do |format|
      format.html { redirect_to interactions_url, notice: 'Interaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interaction
      @interaction = Interaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interaction_params
      params.require(:interaction).permit(:service_id, :name, :link)
    end
end

example/brid/app/helpers/interactions_helper.rb
module InteractionsHelper
end

example/brid/app/views/interactions/_form.html.erb
<%= form_with(model: interaction, local: true) do |form| %>
  <% if interaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interaction.errors.count, "error") %> prohibited this interaction from being saved:</h2>

      <ul>
      <% interaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :service_id %>
    <%= form.number_field :service_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

example/brid/app/views/interactions/edit.html.erb
<h1>Editing Interaction</h1>

<%= render 'form', interaction: @interaction %>

<%= link_to 'Show', @interaction %> |
<%= link_to 'Back', interactions_path %>

example/brid/app/views/interactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interactions</h1>

<table>
  <thead>
    <tr>
      <th>Service</th>
      <th>Name</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interactions.each do |interaction| %>
      <tr>
        <td><%= interaction.service_id %></td>
        <td><%= interaction.name %></td>
        <td><%= interaction.link %></td>
        <td><%= link_to 'Show', interaction %></td>
        <td><%= link_to 'Edit', edit_interaction_path(interaction) %></td>
        <td><%= link_to 'Destroy', interaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interaction', new_interaction_path %>

example/brid/app/views/interactions/new.html.erb
<h1>New Interaction</h1>

<%= render 'form', interaction: @interaction %>

<%= link_to 'Back', interactions_path %>

example/brid/app/views/interactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service:</strong>
  <%= @interaction.service_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @interaction.name %>
</p>

<p>
  <strong>Link:</strong>
  <%= @interaction.link %>
</p>

<%= link_to 'Edit', edit_interaction_path(@interaction) %> |
<%= link_to 'Back', interactions_path %>