brid/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "main/index"
  get "main/export"

  resources :natural_people

  root "main#index"

end

brid/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

brid/app/models/log.rb
class Log < ApplicationRecord
  # belongs_to :type
  # belongs_to :model
  belongs_to :method, optional: true
  belongs_to :model, optional: true
end

brid/app/models/log_method.rb
class LogMethod < ApplicationRecord
end

brid/app/models/log_model.rb
class LogModel < ApplicationRecord
end

brid/app/models/natural_person.rb
class NaturalPerson < ApplicationRecord
  belongs_to :mother, optional: true
  has_many :natural_people, through: :mother
  belongs_to :father, optional: true
  has_many :natural_people, through: :father

  validates :id, exclusion: { in: %w(-1), message: "%{value} is reserved" }
  validates :name, presence: true, 
    length: { 
      within: 3..100, 
      message: "mame's length must be at least 3 and at most 100" 
    }, 
    format: { with: /\w[\w ]\w/, message: "Invalid characters present." }
  validates :identity, presence: true, uniqueness: true
  validates :birth_date, presence: true
  validates :is_male, inclusion: { in: [true, false] }

  validate :gender_change
  validate :valid_mother
  validate :valid_father

  def destroy
    if !NaturalPerson.where(mother_id: id).empty?
      raise "Can't delete mother with children."
    end

    if !NaturalPerson.where(father_id: id).empty?
      raise "Can't delete father with children."
    end

    super
  end

  private
    def gender_change
      if is_male_changed? && self.persisted?
        if (!NaturalPerson.where(mother_id: id).empty? ||
          !NaturalPerson.where(father_id: id).empty?)
          raise "Can't change gender of parents."
        end
      end
    end

    def valid_mother
      if mother_id != nil && NaturalPerson.where(id: mother_id).empty?
        raise "Mother doesn't exist."
      end
    end

    def valid_father
      if father_id != nil && NaturalPerson.where(id: father_id).empty?
        raise "Father doesn't exist."
      end
    end
end

brid/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

brid/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @logs = Log.all.order(created_at: :desc).limit(10)
  end

  def export
    output = ""

    data = NaturalPerson.all.to_a.map(&:attributes)
    data.each {|x| x.delete("id")}
    data.each {|x| x["birth_date"] = x["birth_date"].to_i}
    data.each {|x| x["created_at"] = x["created_at"].to_i}
    data.each {|x| x["updated_at"] = x["updated_at"].to_i}
    output += data.to_yaml.to_s + "\n\n"

    data = Log.all.to_a.map(&:attributes)
    data.each {|x| x.delete("id")}
    data.each {|x| x["created_at"] = x["created_at"].to_i}
    data.each {|x| x["updated_at"] = x["updated_at"].to_i}
    output += data.to_yaml.to_s + "\n\n"

    render plain: output
  end
end

brid/app/controllers/natural_people_controller.rb
class NaturalPeopleController < ApplicationController
  before_action :set_natural_person, only: [:show, :edit, :update, :destroy]

  # GET /natural_people
  # GET /natural_people.json
  def index
    @natural_people = NaturalPerson.all

    Log.create!(
      method_id: LogMethod.where(method: "QUERY").first.id,
      model_id: LogModel.where(model: "NaturalPerson").first.id,
      description: "LIST ALL"
    )
  end

  # GET /natural_people/1
  # GET /natural_people/1.json
  def show
    Log.create!(
      method_id: LogMethod.where(method: "INSPECT").first.id,
      model_id: LogModel.where(model: "NaturalPerson").first.id,
      description: "INSPECT " + @natural_person.inspect.to_s
    )
  end

  # GET /natural_people/new
  def new
    @natural_person = NaturalPerson.new
    @natural_people = NaturalPerson.all
  end

  # GET /natural_people/1/edit
  def edit
  end

  # POST /natural_people
  # POST /natural_people.json
  def create
    # render plain: params
    # params.permit!
    @natural_person = NaturalPerson.new(natural_person_params)

    respond_to do |format|
      if @natural_person.save
        format.html { redirect_to @natural_person, notice: "Natural Person was successfully created." }
        format.json { render :show, status: :created, location: @natural_person }

        Log.create!(
          method_id: LogMethod.where(method: "CREATE").first.id,
          model_id: LogModel.where(model: "NaturalPerson").first.id,
          description: "CREATED " + @natural_person.inspect.to_s
        )
      else
        format.html { render :new }
        format.json { render json: @natural_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /natural_people/1
  # PATCH/PUT /natural_people/1.json
  def update
    respond_to do |format|
      if @natural_person.update(natural_person_params)
        format.html { redirect_to @natural_person, notice: "Natural Person was successfully updated." }
        format.json { render :show, status: :ok, location: @natural_person }

        Log.create!(
          method_id: LogMethod.where(method: "UPDATE").first.id,
          model_id: LogModel.where(model: "NaturalPerson").first.id,
          description: "UPDATED " + @natural_person.inspect.to_s
        )
      else
        format.html { render :edit }
        format.json { render json: @natural_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /natural_people/1
  # DELETE /natural_people/1.json
  def destroy
    @natural_person.destroy

    Log.create!(
      method_id: LogMethod.where(method: "DELETE").first.id,
      model_id: LogModel.where(model: "NaturalPerson").first.id,
      description: "DELETED " + @natural_person.inspect.to_s
    )

    respond_to do |format|
      format.html { redirect_to natural_people_url, notice: "Natural Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_natural_person
      @natural_person = NaturalPerson.find(params[:id])
      @natural_people = NaturalPerson.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def natural_person_params
      params.require(:natural_person).permit(
        :name, 
        :identity, 
        "birth_date(1i)",
        "birth_date(2i)",
        "birth_date(3i)",
        :gender
      )
      params.require(:mother_id)
      params.require(:father_id)

      name = params[:natural_person][:name]
      identity = params[:natural_person][:identity]
      birth_date = DateTime.new(
        params[:natural_person]["birth_date(1i)"].to_i,
        params[:natural_person]["birth_date(2i)"].to_i,
        params[:natural_person]["birth_date(3i)"].to_i
      )
      is_male = params[:natural_person][:gender] == "male"
      mother_id = params[:mother_id].to_i
      father_id = params[:father_id].to_i

      permitted = {
        name: name, 
        identity: identity, 
        birth_date: birth_date,
        is_male: is_male
      }

      if mother_id != -1
        permitted[:mother_id] = mother_id
      end
  
      if father_id != -1
        permitted[:father_id] = father_id
      end

      permitted
    end
end

brid/app/helpers/application_helper.rb
module ApplicationHelper
end

brid/app/helpers/log_methods_helper.rb
module LogMethodsHelper
end

brid/app/helpers/log_models_helper.rb
module LogModelsHelper
end

brid/app/helpers/logs_helper.rb
module LogsHelper
end

brid/app/helpers/main_helper.rb
module MainHelper
end

brid/app/helpers/natural_people_helper.rb
module NaturalPeopleHelper
end

brid/app/views/main/index.html.erb
<h1>BRID</h1>
<p>A suggestion for Brazil's legal person identifier and unified sensitive information handler</p>

<h2>Natural Person handlers</h2>
<ul>
  <li><a href="/natural_people">Show all</a></li>
  <li><a href="/natural_people/new">Register</a></li>
</ul>

<h2>Logs</h2>
<table>
  <thead>
    <tr>
      <th>When</th>
      <th>Method</th>
      <th>Model</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.created_at %></td>
        <td><%= LogMethod.find(log.method_id).method %></td>
        <td><%= LogModel.find(log.model_id).model %></td>
        <td><%= log.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

brid/app/views/natural_people/_form.html.erb
<%= form_with(model: natural_person, local: true) do |form| %>
  <% if natural_person.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(natural_person.errors.count, "error") %> 
        prohibited this natural_person from being saved:
      </h2>

      <ul>
      <% natural_person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tbody>
      <tr>
        <td><%= form.label :name %></td>
        <td><%= form.text_field :name %></td>
      </tr>
      <tr>
        <td><%= form.label :identity %></td>
        <td><%= form.text_field :identity %></td>
      </tr>
      <tr>
        <td><%= form.label :birth_date, "Birthdate" %></td>
        <td><%= form.date_select :birth_date, :start_year => 1800 %></td>
      </tr>
      <tr>
        <td><%= form.label :gender %></td>
        <td>
          <%= form.radio_button :gender, :male, :checked => true %>
          <%= form.label :male, :value => :male %>
          <%= form.radio_button :gender, :female %>
          <%= form.label :female, :value => :female %>
        </td>
      </tr>
      <tr>
        <td><%= form.label :mother_id %></td>
        <td><%= 
          select_tag(
            :mother_id, options_for_select([["(undefined)", "-1"]]) + 
            options_from_collection_for_select(@natural_people.where(is_male: false), :id, :name)
          )
        %></td>
      </tr>
      <tr>
        <td><%= form.label :father_id %></td>
        <td><%= 
          select_tag(
            :father_id, options_for_select([["(undefined)", "-1"]]) + 
            options_from_collection_for_select(@natural_people.where(is_male: true), :id, :name)
          )
        %></td>
      </tr>
      <tr>
        <td><%= form.submit "Save" %></td>
      </tr>
    </tbody>
  </table>
<% end %>

brid/app/views/natural_people/edit.html.erb
<h1>Editing Natural Person</h1>

<%= render "form", natural_person: @natural_person %>

<%= link_to "Show", @natural_person %> |
<%= link_to "Back", natural_people_path %>

brid/app/views/natural_people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Natural People</h1>

<table>
  <thead>
      <tr>
        <%- NaturalPerson.new.attributes.each do |key, value| %>
          <th><%= key %></th>
        <% end %>
      </tr>
  </thead>
  <tbody>
    <%- @natural_people.each do |natural_person| %>
      <tr>
        <%- natural_person.attributes.each do |key, value| %>
          <td><%= value %></td>
        <% end %>
        <td><%= link_to "INSPECT", natural_person %></td>
        <td><%= link_to "EDIT", edit_natural_person_path(natural_person) %></td>
        <td>
          <%= 
            link_to "DELETE", natural_person, method: :delete,
            data: { confirm: "Are you sure?"}
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "CREATE", new_natural_person_path %>

brid/app/views/natural_people/new.html.erb
<h1>New natural person</h1>

<%= render "form", natural_person: @natural_person %>

<%= link_to "Back", natural_people_path %>

brid/app/views/natural_people/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Natural Person</h1>

<table>
  <%- @natural_person.attributes.each do |key, value| %>
    <tr>
      <td><b><%= key %></b></td>
      <td><%= value %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Edit", edit_natural_person_path(@natural_person) %> |
<%= link_to "Back", natural_people_path %>