example/urbanbus/config/routes.rb
Rails.application.routes.draw do
  resources :users

  post "users/connect"
  post "users/answer"
  post "users/query"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "main/index"

  root "main#index"
end

example/urbanbus/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

example/urbanbus/app/models/response.rb
class Response < ApplicationRecord
end

example/urbanbus/app/models/user.rb
class User < ApplicationRecord
end

example/urbanbus/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

example/urbanbus/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

example/urbanbus/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, :only => [:connect, :query, :answer]
  add_flash_types :error

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def connect
    params.permit!

    if User.where(brid: params[:id]).empty?
      @user = User.new(
        brid: params[:id],
        name: params[:name]
      )

      notice = 'Welcome, ' + params[:name] + '!'

      if @user.save
        redirect_to @user, notice: notice
      end
    else
      @user = User.where(brid: params[:id]).first

      notice = 'Welcome back, ' + params[:name] + '!'

      redirect_to @user, notice: notice
    end
  end

  def query
    config.allow_concurrency=true
  
    params.require(:id)

    @user = User.find(params[:id])

    require "net/http"
    require "json"

    # @response = Response.create(waiting: true)

    uri = URI("http://localhost:3000/main/interact")
    http = Net::HTTP.new(uri.host, uri.port)
    req = Net::HTTP::Post.new(uri.path)
    req.set_form_data({
      brid: @user.brid.to_s,
      from_id: 2,
      key: "urbanbussecretkey",
      to_id: 1,
      interaction: "debit",
      interact: "http://localhost:3001/clients/debit",
      data: "3.0",
      request: 1, #@response.id,
      callback: "http://localhost:3002/users/answer"
    })
    res = http.request(req)

    # while Response.find(:id).waiting
    #   sleep(1)
    # end


    if res.body == "true"
      redirect_to @user, notice: "Transaction acepted."
    elsif res.body.to_s == "false"
      redirect_to @user, error: "Trasaction refused."
    else
      render plain: res.body.to_s
    end

    # render plain: res.body
    # render plain: User.find(2).name

    # if res.body.to_s == "true"
    #   render plain: "okay"
    # elsif res.body.to_s == "false"
    #   render plain: "no"
    # end
  end

  def answer
    params.permit!

    # @response = Response.find params[:request]

    # @response.update waiting: false, accepted: params[:response].to_s == "true"
    # @response.update waiting: false

    # render plain: User.all.to_s
    # render plain: params.inspect
    render plain: params.inspect
    # render plain: params[:response]
    # render plain: Response.find(id: params[:resquest]).id
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:brid, :name)
    end
end

example/urbanbus/app/helpers/application_helper.rb
module ApplicationHelper
end

example/urbanbus/app/helpers/main_helper.rb
module MainHelper
end

example/urbanbus/app/helpers/users_helper.rb
module UsersHelper
end

example/urbanbus/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Urbanbus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <ul>
      <li><a href="/">Index</a></li>
      <li><a href="/users">Users</a></li>
    </ul>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

example/urbanbus/app/views/main/index.html.erb
<h1>UrbanBus</h1>

<form action="http://localhost:3000/main/connect" method="post">
  <%# this is only a test. The real interaction shall use only id and key %>
  <%# <input type="hidden" name="id" value="?" /> %>
  <%# <input type="hidden" name="key" value="?" /> %>
  <input type="hidden" name="name" value="UrbanBus" />
  <input type="hidden" name="callback" value="http://localhost:3002/users/connect" />
  <input type="submit" value="Enter with brid" />
</form>

example/urbanbus/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brid %>
    <%= form.number_field :brid %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

example/urbanbus/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

example/urbanbus/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Brid</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.brid %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

example/urbanbus/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

example/urbanbus/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p id="error" style="color: red"><%= error %></p>

<p>
  <strong>Brid:</strong>
  <%= @user.brid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<!---
<form action="http://localhost:3000/main/interact" method="post">
  <%# this is only a test. The real interaction shall use only id and key %>
  <%# <input type="hidden" name="id" value="?" /> %>
  <%# <input type="hidden" name="key" value="?" /> %>
  <input type="hidden" name="brid" value="<%= @user.brid %>" />
  <input type="hidden" name="name" value="UrbanBus" />
  <input type="hidden" name="interact" value="http://localhost:3001/clients/debit" />
  <input type="hidden" name="data" value="3" />
  <input type="hidden" name="request" value="1" />
  <input type="hidden" name="callback" value="http://localhost:3002/users/answer" />
  <input type="submit" value="Pay fare: $3" />
</form>
-->

<form action="/users/query" method="post">
  <input type="hidden" name="id" value="<%= @user.id %>" />
  <input type="submit" value="Pay fare: $3" />
</form>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>